In [10]:
import numpy as np
def range_squre_matrix(n):

    matrix = np.zeros((n, n), dtype=np.int32)
    for i in range(n):
        matrix[i,:] = np.arange(i, n+i, 1)
    return matrix

range_squre_matrix(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]], dtype=int32)

In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a[1:4] = 5,5,5
# a[1:4] = 6 # error
print(a)

[1, 5, 5, 5, 5, 6, 7, 8, 9]


In [16]:
a = np.arange(9).reshape(3, 3)
print(a)
print(a.ndim)
print(a[:2, :2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2
[[0 1]
 [3 4]]


In [18]:
for idx, e  in np.ndenumerate(np.arange(3)):
    print(idx, e)
for idx, e  in np.ndenumerate(np.arange(6).reshape(2, 3)):
    print(idx, e)

(0,) 0
(1,) 1
(2,) 2
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
